#!/usr/bin/env bash
# This script displays the username, user id and home directory of each user in /etc/passwd
while IFS=: read -r user _ uid _ _ home _; do
    echo "$user:$uid:$home"
done < /etc/passwd
